
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    custom_components.yongnuo_yn360: debug
    homeassistant.components.bluetooth: debug
    homeassistant.components.light: debug
    habluetooth: debug
    bluetooth_adapters: debug
    bluetooth_auto_recovery: debug
    bleak: debug
    bleak.backends.bluezdbus: debug
    bleak_retry_connector: debug
    dbus_fast: debug

homekit:
  - name: YN150 RGB 4260
    port: 21063
    mode: accessory
    filter:
      include_entities:
        - light.yn360_led_video_light_db_b9_85_86_42_60
    entity_config:
      light.yn360_led_video_light_db_b9_85_86_42_60:
        name: YN150 RGB 4260
  - name: YN150 WY 7449
    port: 21064
    mode: accessory
    filter:
      include_entities:
        - light.yn360_led_video_light_d0_32_34_39_74_49
    entity_config:
      light.yn360_led_video_light_d0_32_34_39_74_49:
        name: YN150 WY 7449
  - name: YN150 RGB 6D6F
    port: 21065
    mode: accessory
    filter:
      include_entities:
        - light.yn360_led_video_light_d0_32_34_39_6d_6f
    entity_config:
      light.yn360_led_video_light_d0_32_34_39_6d_6f:
        name: YN150 RGB 6D6F
