DOMAIN = "yongnuo_yn360"

CONF_ADDRESS = "address"
CONF_MODEL = "model"
CONF_IDLE_DISCONNECT_SECONDS = "idle_disconnect_seconds"

MODEL_YN360 = "yn360"
MODEL_YN150 = "yn150"
MODEL_YN150RGB = "yn150rgb"
DEFAULT_MODEL = MODEL_YN360

DATA_BLE_SLOT_SEMAPHORE = "ble_slot_semaphore"
DEFAULT_IDLE_DISCONNECT_SECONDS = 3.0
MAX_IDLE_DISCONNECT_SECONDS = 12.0
SHARED_BLE_CONNECTION_LIMIT = 1
BLE_DISCONNECT_TIMEOUT_SECONDS = 2.0
BLE_SLOT_ACQUIRE_TIMEOUT_SECONDS = 8.0

MIN_COLOR_TEMP_KELVIN = 3200
MAX_COLOR_TEMP_KELVIN = 5500
MAX_WHITE_LEVEL = 99
